import {User} from './user';
export class Repo {
  id: number;
  full_name: string;
  name: string;
  owner:User;
  private : boolean;
  html_url : string;
  description : string;
  fork : boolean;
  forks_url : string;
  keys_url : string;
  url : string;
  deployments_url : string;
  releases_url : string;
  created_at : Date;
  updated_at : Date;
  pushed_at : Date;
  git_url : string;
  ssh_url : string;
  clone_url : string;
  svn_url : string;
  homepage : string;
  size : number;
  stargazers_count : number;
  watchers_count : number;
  language : string;
  has_issues : boolean;
  has_downloads : boolean;
  has_wiki : boolean;
  has_pages : boolean;
  forks_count : number;
  open_issues_count : number;
  forks : number;
  open_issues : number;
  watchers : number;
  default_branch : string ;
  collaborators_url : string;
  teams_url : string;
  hooks_url : string;
  issue_events_url : String;
  events_url : String;
  assignees_url : String;
  branches_url : String;
  tags_url : String;
  blobs_url : String;
  git_tags_url : String;
  git_refs_url : String;
  trees_url : String;
  languages_url : String;
  stargazers_url : String;
  contributors_url : String;
  subscribers_url : String;
  subscription_url : String;
  commits_url : String;
  git_commits_url : String;
  comments_url : String;
  issue_comment_url : String;
  contents_url : String;
  compare_url : String;
  merges_url : String;
  archive_url : String;
  downloads_url : String;
  issues_url : String;
  pulls_url : String;
  milestones_url : String;
  notifications_url : String;
  labels_url : String;
  statuses_url: string;
  mirror_url : String;
}